# Configuração do Netlify para projeto Angular
[build]
  # Diretório onde o comando de build será executado
  base = "/"
  
  # Comando para construir o projeto
  command = "npm run build:prod"
  
  # Diretório que será publicado (output do Angular)
  publish = "dist/maple-erp-frontend/browser"

# Configurações de ambiente de produção
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Variáveis de ambiente para build
  VITE_APP_ENVIRONMENT = "production"
  VITE_API_URL_PROD = "https://maple-erp-backend.onrender.com"
  VITE_APP_NAME = "Maple ERP Frontend"
  VITE_APP_VERSION = "1.0.0"
  VITE_ENABLE_DEBUG_LOGS = "false"
  VITE_ENABLE_HTTPS_ONLY = "true"

# Redirecionamentos para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeçalhos de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: https://res.cloudinary.com; connect-src 'self' https://maple-erp-backend.onrender.com; manifest-src 'self';"
