# Configuração do Netlify para projeto Angular
[build]
  # Diretório onde o comando de build será executado
  base = "/"
  
  # Comando para construir o projeto
  command = "npm run build:prod"
  
  # Diretório que será publicado (output do Angular)
  publish = "dist/maple-erp-frontend/browser"

# Configurações de ambiente de produção
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Variáveis de ambiente para build - TODAS as variáveis necessárias
  VITE_APP_ENVIRONMENT = "production"
  VITE_API_URL_DEV = "http://localhost:4000"
  VITE_API_URL_PROD = "https://maple-erp-backend.onrender.com"
  VITE_APP_NAME = "Maple ERP Frontend"
  VITE_APP_VERSION = "1.0.0"
  VITE_API_EMPLOYEES_ENDPOINT = "/employees"
  VITE_API_HEALTH_ENDPOINT = "/health-check"
  VITE_API_TEMPLATE_ENDPOINT = "/template-cracha"
  VITE_MAX_FILE_SIZE = "5242880"
  VITE_ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/jpg"
  VITE_DEFAULT_PAGE_SIZE = "20"
  VITE_MAX_PAGE_SIZE = "100"
  VITE_DEFAULT_LANGUAGE = "pt-BR"
  VITE_DATE_FORMAT = "DD/MM/YYYY"
  VITE_CURRENCY = "BRL"
  VITE_ENABLE_DEBUG_LOGS = "false"
  VITE_ENABLE_MOCK_DATA = "false"
  VITE_ENABLE_HTTPS_ONLY = "true"
  VITE_SESSION_TIMEOUT = "3600000"
  VITE_ENABLE_HEALTH_CHECK = "true"
  VITE_ENABLE_EXPORT_FEATURES = "true"
  VITE_ENABLE_BADGE_GENERATION = "true"
  VITE_ENABLE_MULTIPLE_BADGE_GENERATION = "true"
  VITE_DEFAULT_ERROR_MESSAGE = "Ocorreu um erro inesperado. Tente novamente."
  VITE_NETWORK_ERROR_MESSAGE = "Erro de conexão. Verifique sua internet."
  VITE_SERVER_ERROR_MESSAGE = "Erro interno do servidor. Tente novamente mais tarde."
  VITE_LOADING_TIMEOUT = "30000"
  VITE_REQUEST_TIMEOUT = "10000"

# Redirecionamentos para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeçalhos de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: https://res.cloudinary.com; connect-src 'self' https://maple-erp-backend.onrender.com; manifest-src 'self';"
