# Configuração do Netlify para projeto Angular
[build]
  # Diretório onde o comando de build será executado
  base = "/"
  
  # Comando para construir o projeto
  command = "npm run build"
  
  # Diretório que será publicado (output do Angular)
  publish = "dist/maple-erp-frontend/browser"

# Configurações de ambiente de produção
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Redirecionamentos para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeçalhos de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; connect-src 'self' http://localhost:4000 https://api.maple-erp.com; manifest-src 'self';"
